spring.application.name=prodigo-erp

# jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:jobportal}
spring.datasource.url=jdbc:postgresql://localhost:5432/prodigodb
spring.datasource.username=postgres
spring.datasource.password=@azerty237
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=
spring.jpa.show-sql=true
